# Generated by Django 3.1.5 on 2021-11-26 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0007_auto_20211126_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transfer',
            name='desc',
            field=models.CharField(default='Nil', max_length=200),
        ),
    ]
